### ISSUE TITLE
Use debug instead of console.log

### ISSUE THREAD

**Issue by PoolloverNathan** [nomorenotes/nomorenotes#189]
**Is your feature request related to a problem? Please describe.**
We currently use console.log instead of a better library like [`debug`](https://npmjs.com/debug). This makes it hard to see at a glance what is happening

**Describe the solution you'd like**
Each type of message should have a logger, and console.log should be removed from the codebase.

**Comment by PoolloverNathan** [comment]
```
TypeError: (Math.random(...).toString(...).split(...)[1] || "").splice is not a function
    at /home/runner/nomorenotes/server.js:78:66
    at Layer.handle [as handle_request] (/home/runner/nomorenotes/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/nomorenotes/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/runner/nomorenotes/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/runner/nomorenotes/node_modules/express/lib/router/layer.js:95:5)
    at /home/runner/nomorenotes/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/runner/nomorenotes/node_modules/express/lib/router/index.js:341:12)
    at next (/home/runner/nomorenotes/node_modules/express/lib/router/index.js:275:10)
    at rawParser (/home/runner/nomorenotes/node_modules/body-parser/lib/types/raw.js:67:7)
    at Layer.handle [as handle_request] (/home/runner/nomorenotes/node_modules/express/lib/router/layer.js:95:5)
TypeError: (Math.random(...).toString(...).split(...)[1] || "").splice is not a function
    at /home/runner/nomorenotes/server.js:78:66
    at Layer.handle [as handle_request] (/home/runner/nomorenotes/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/nomorenotes/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/runner/nomorenotes/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/runner/nomorenotes/node_modules/express/lib/router/layer.js:95:5)
    at /home/runner/nomorenotes/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/runner/nomorenotes/node_modules/express/lib/router/index.js:341:12)
    at next (/home/runner/nomorenotes/node_modules/express/lib/router/index.js:275:10)
    at rawParser (/home/runner/nomorenotes/node_modules/body-parser/lib/types/raw.js:67:7)
    at Layer.handle [as handle_request] (/home/runner/nomorenotes/node_modules/express/lib/router/layer.js:95:5)
```
